'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("guna_form.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1defe1c08e139a4a534f23676e1a534b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1defe1c08e139a4a534f23676e1a534b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _35c11477d386737c8890f6cc0c0cd2d7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("35c11477d386737c8890f6cc0c0cd2d7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5545a2a9ce938ec70e0941cdd7a82105() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5545a2a9ce938ec70e0941cdd7a82105", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _809da62dfa7f9a1a1bfbdd1e40fa36ae() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("809da62dfa7f9a1a1bfbdd1e40fa36ae", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _809da62dfa7f9a1a1bfbdd1e40fa36ae1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("809da62dfa7f9a1a1bfbdd1e40fa36ae1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8e9be8eab623d1a87cd696a5918af8af() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8e9be8eab623d1a87cd696a5918af8af", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property a04bd86dfd53eaf0e73264180f867dc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a04bd86dfd53eaf0e73264180f867dc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property b2baf2fab26ca590e0043a3d420bd920() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b2baf2fab26ca590e0043a3d420bd920", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property b864854975f3621d28a975f237556419() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b864854975f3621d28a975f237556419", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c56fb3ba335505a88fbfcba7ab63d618() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c56fb3ba335505a88fbfcba7ab63d618", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cc316f97197528e5e26e613a93ab16a4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cc316f97197528e5e26e613a93ab16a4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d8d4791ec64f0e040111ef014475f2ba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d8d4791ec64f0e040111ef014475f2ba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dbcc3155fe447fdfa63a9d62aa6a341d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dbcc3155fe447fdfa63a9d62aa6a341d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property e99414070fabc44ae9ed2b470c71300a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("e99414070fabc44ae9ed2b470c71300a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f41e2dab621c1ee5253cef74e3642fcf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f41e2dab621c1ee5253cef74e3642fcf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fb50f0543aa72a4b35e1077ec58571ce() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fb50f0543aa72a4b35e1077ec58571ce", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fec00ad72bc5bb2ccd2332ae35ccd4cc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fec00ad72bc5bb2ccd2332ae35ccd4cc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fec00ad72bc5bb2ccd2332ae35ccd4cc1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fec00ad72bc5bb2ccd2332ae35ccd4cc1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
